services:
  backend:
    build:
      context: ./back
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CORS_URL=http://91.227.68.159
    volumes:
      # Монтирование папки с моделями
      - ./back/models:/app/models:ro
      # Монтирование папки с данными
      - ./back/data:/app/data
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./front
    ports:
      - "80:8080"
    volumes:
      # Монтирование папки с фото
      - ./back/data/photo:/usr/share/nginx/html/data/photo
      # Монтирование папки с груповыми фото
      - ./back/data/reports:/usr/share/nginx/html/data/reports
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
