// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_create_reference_students__student_id__photos__post
 */
export type BodyCreateReferenceStudentsStudentIdPhotosPost = {
    /**
     * Photo
     */
    photo: Blob | File;
};

/**
 * Body_create_result_reports__post
 */
export type BodyCreateResultReportsPost = {
    /**
     * Data
     */
    data: RecognitionDataCreate | string;
    /**
     * Photo
     */
    photo: Blob | File;
};

/**
 * Body_login_for_access_token_token__post
 */
export type BodyLoginForAccessTokenTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * GroupCreate
 */
export type GroupCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Stream Id
     */
    stream_id: number;
};

/**
 * GroupPublic
 */
export type GroupPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Stream Id
     */
    stream_id: number;
    /**
     * Id
     */
    id: number;
};

/**
 * GroupPublicWithStream
 */
export type GroupPublicWithStream = {
    /**
     * Name
     */
    name: string;
    /**
     * Stream Id
     */
    stream_id: number;
    /**
     * Id
     */
    id: number;
    stream: StreamPublic;
};

/**
 * GroupUpdate
 */
export type GroupUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Stream Id
     */
    stream_id?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RecognitionDataCreate
 */
export type RecognitionDataCreate = {
    /**
     * Lecture Date
     */
    lecture_date?: string;
    /**
     * Lecture Num
     */
    lecture_num: number;
};

/**
 * RecognitionDataPublic
 */
export type RecognitionDataPublic = {
    /**
     * Lecture Date
     */
    lecture_date?: string;
    /**
     * Lecture Num
     */
    lecture_num: number;
    /**
     * Id
     */
    id: number;
    /**
     * Image Path
     */
    image_path: string;
};

/**
 * RecognitionDataPublicWithRecognitionResultAndStudent
 */
export type RecognitionDataPublicWithRecognitionResultAndStudent = {
    /**
     * Lecture Date
     */
    lecture_date?: string;
    /**
     * Lecture Num
     */
    lecture_num: number;
    /**
     * Id
     */
    id: number;
    /**
     * Image Path
     */
    image_path: string;
    /**
     * Results
     */
    results: Array<RecognitionResultPublicWithStudent>;
};

/**
 * RecognitionResultPublicWithStudent
 */
export type RecognitionResultPublicWithStudent = {
    /**
     * Student Id
     */
    student_id?: number | null;
    /**
     * Data Id
     */
    data_id: number;
    /**
     * Bbox X1
     */
    bbox_x1: number;
    /**
     * Bbox Y1
     */
    bbox_y1: number;
    /**
     * Bbox X2
     */
    bbox_x2: number;
    /**
     * Bbox Y2
     */
    bbox_y2: number;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Similarity
     */
    similarity?: number | null;
    /**
     * Id
     */
    id: number;
    student?: StudentPublic | null;
};

/**
 * RecognitionResultUpdate
 */
export type RecognitionResultUpdate = {
    /**
     * Student Id
     */
    student_id?: number | null;
    /**
     * Similarity
     */
    similarity?: null;
};

/**
 * ReferenceFacePublic
 */
export type ReferenceFacePublic = {
    /**
     * Student Id
     */
    student_id: number;
    /**
     * Id
     */
    id: number;
    /**
     * Image Path
     */
    image_path: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * StreamCreate
 */
export type StreamCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * StreamPublic
 */
export type StreamPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: number;
};

/**
 * StreamUpdate
 */
export type StreamUpdate = {
    [key: string]: unknown;
};

/**
 * StudentCreate
 */
export type StudentCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Group Id
     */
    group_id: number;
    /**
     * Phone Number
     */
    phone_number?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * StudentPrivate
 */
export type StudentPrivate = {
    /**
     * Name
     */
    name: string;
    /**
     * Group Id
     */
    group_id: number;
    /**
     * Id
     */
    id: number;
    /**
     * Phone Number
     */
    phone_number: string | null;
    /**
     * Email
     */
    email: string | null;
};

/**
 * StudentPublic
 */
export type StudentPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Group Id
     */
    group_id: number;
    /**
     * Id
     */
    id: number;
};

/**
 * StudentPublicWithGroup
 */
export type StudentPublicWithGroup = {
    /**
     * Name
     */
    name: string;
    /**
     * Group Id
     */
    group_id: number;
    /**
     * Id
     */
    id: number;
    group: GroupPublic;
};

/**
 * StudentUpdate
 */
export type StudentUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Group Id
     */
    group_id?: number | null;
    /**
     * Phone Number
     */
    phone_number?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * User Name
     */
    user_name: string;
    /**
     * Role Id
     */
    role_id: number | null;
    /**
     * Student Id
     */
    student_id?: number | null;
    /**
     * Group Id
     */
    group_id?: number | null;
    /**
     * Stream Id
     */
    stream_id?: number | null;
    /**
     * Id
     */
    id: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadStreamsStreamsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/streams/';
};

export type ReadStreamsStreamsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadStreamsStreamsGetError = ReadStreamsStreamsGetErrors[keyof ReadStreamsStreamsGetErrors];

export type ReadStreamsStreamsGetResponses = {
    /**
     * Response Read Streams Streams  Get
     *
     * Successful Response
     */
    200: Array<StreamPublic>;
};

export type ReadStreamsStreamsGetResponse = ReadStreamsStreamsGetResponses[keyof ReadStreamsStreamsGetResponses];

export type CreateStreamStreamsPostData = {
    body: StreamCreate;
    path?: never;
    query?: never;
    url: '/streams/';
};

export type CreateStreamStreamsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStreamStreamsPostError = CreateStreamStreamsPostErrors[keyof CreateStreamStreamsPostErrors];

export type CreateStreamStreamsPostResponses = {
    /**
     * Successful Response
     */
    201: StreamPublic;
};

export type CreateStreamStreamsPostResponse = CreateStreamStreamsPostResponses[keyof CreateStreamStreamsPostResponses];

export type DeleteStreamStreamsStreamIdDeleteData = {
    body?: never;
    path: {
        /**
         * ID потока для удаления
         */
        stream_id: number;
    };
    query?: never;
    url: '/streams/{stream_id}';
};

export type DeleteStreamStreamsStreamIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteStreamStreamsStreamIdDeleteError = DeleteStreamStreamsStreamIdDeleteErrors[keyof DeleteStreamStreamsStreamIdDeleteErrors];

export type DeleteStreamStreamsStreamIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadStreamStreamsStreamIdGetData = {
    body?: never;
    path: {
        /**
         * ID потока для получения
         */
        stream_id: number;
    };
    query?: never;
    url: '/streams/{stream_id}';
};

export type ReadStreamStreamsStreamIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadStreamStreamsStreamIdGetError = ReadStreamStreamsStreamIdGetErrors[keyof ReadStreamStreamsStreamIdGetErrors];

export type ReadStreamStreamsStreamIdGetResponses = {
    /**
     * Successful Response
     */
    200: StreamPublic;
};

export type ReadStreamStreamsStreamIdGetResponse = ReadStreamStreamsStreamIdGetResponses[keyof ReadStreamStreamsStreamIdGetResponses];

export type UpdateStreamStreamsStreamIdPutData = {
    body: StreamUpdate;
    path: {
        /**
         * ID потока для изменения
         */
        stream_id: number;
    };
    query?: never;
    url: '/streams/{stream_id}';
};

export type UpdateStreamStreamsStreamIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStreamStreamsStreamIdPutError = UpdateStreamStreamsStreamIdPutErrors[keyof UpdateStreamStreamsStreamIdPutErrors];

export type UpdateStreamStreamsStreamIdPutResponses = {
    /**
     * Successful Response
     */
    200: StreamPublic;
};

export type UpdateStreamStreamsStreamIdPutResponse = UpdateStreamStreamsStreamIdPutResponses[keyof UpdateStreamStreamsStreamIdPutResponses];

export type ReadGroupsGroupsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Stream Id
         */
        stream_id?: number | null;
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/groups/';
};

export type ReadGroupsGroupsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadGroupsGroupsGetError = ReadGroupsGroupsGetErrors[keyof ReadGroupsGroupsGetErrors];

export type ReadGroupsGroupsGetResponses = {
    /**
     * Response Read Groups Groups  Get
     *
     * Successful Response
     */
    200: Array<GroupPublicWithStream>;
};

export type ReadGroupsGroupsGetResponse = ReadGroupsGroupsGetResponses[keyof ReadGroupsGroupsGetResponses];

export type CreateGroupGroupsPostData = {
    body: GroupCreate;
    path?: never;
    query?: never;
    url: '/groups/';
};

export type CreateGroupGroupsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGroupGroupsPostError = CreateGroupGroupsPostErrors[keyof CreateGroupGroupsPostErrors];

export type CreateGroupGroupsPostResponses = {
    /**
     * Successful Response
     */
    201: GroupPublicWithStream;
};

export type CreateGroupGroupsPostResponse = CreateGroupGroupsPostResponses[keyof CreateGroupGroupsPostResponses];

export type DeleteGroupGroupsGroupIdDeleteData = {
    body?: never;
    path: {
        /**
         * ID группы для удаления
         */
        group_id: number;
    };
    query?: never;
    url: '/groups/{group_id}';
};

export type DeleteGroupGroupsGroupIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGroupGroupsGroupIdDeleteError = DeleteGroupGroupsGroupIdDeleteErrors[keyof DeleteGroupGroupsGroupIdDeleteErrors];

export type DeleteGroupGroupsGroupIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadGroupGroupsGroupIdGetData = {
    body?: never;
    path: {
        /**
         * ID группы для получения
         */
        group_id: number;
    };
    query?: never;
    url: '/groups/{group_id}';
};

export type ReadGroupGroupsGroupIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadGroupGroupsGroupIdGetError = ReadGroupGroupsGroupIdGetErrors[keyof ReadGroupGroupsGroupIdGetErrors];

export type ReadGroupGroupsGroupIdGetResponses = {
    /**
     * Successful Response
     */
    200: GroupPublicWithStream;
};

export type ReadGroupGroupsGroupIdGetResponse = ReadGroupGroupsGroupIdGetResponses[keyof ReadGroupGroupsGroupIdGetResponses];

export type UpdateGroupGroupsGroupIdPutData = {
    body: GroupUpdate;
    path: {
        /**
         * ID группы для изменения
         */
        group_id: number;
    };
    query?: never;
    url: '/groups/{group_id}';
};

export type UpdateGroupGroupsGroupIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateGroupGroupsGroupIdPutError = UpdateGroupGroupsGroupIdPutErrors[keyof UpdateGroupGroupsGroupIdPutErrors];

export type UpdateGroupGroupsGroupIdPutResponses = {
    /**
     * Successful Response
     */
    200: GroupPublicWithStream;
};

export type UpdateGroupGroupsGroupIdPutResponse = UpdateGroupGroupsGroupIdPutResponses[keyof UpdateGroupGroupsGroupIdPutResponses];

export type ReadStudentsStudentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Group Id
         */
        group_id?: number | null;
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/students/';
};

export type ReadStudentsStudentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadStudentsStudentsGetError = ReadStudentsStudentsGetErrors[keyof ReadStudentsStudentsGetErrors];

export type ReadStudentsStudentsGetResponses = {
    /**
     * Response Read Students Students  Get
     *
     * Successful Response
     */
    200: Array<StudentPublicWithGroup>;
};

export type ReadStudentsStudentsGetResponse = ReadStudentsStudentsGetResponses[keyof ReadStudentsStudentsGetResponses];

export type CreateStudentStudentsPostData = {
    body: StudentCreate;
    path?: never;
    query?: never;
    url: '/students/';
};

export type CreateStudentStudentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStudentStudentsPostError = CreateStudentStudentsPostErrors[keyof CreateStudentStudentsPostErrors];

export type CreateStudentStudentsPostResponses = {
    /**
     * Successful Response
     */
    201: StudentPublic;
};

export type CreateStudentStudentsPostResponse = CreateStudentStudentsPostResponses[keyof CreateStudentStudentsPostResponses];

export type DeleteStudentStudentsStudentIdDeleteData = {
    body?: never;
    path: {
        /**
         * ID студента для удаления
         */
        student_id: number;
    };
    query?: never;
    url: '/students/{student_id}';
};

export type DeleteStudentStudentsStudentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteStudentStudentsStudentIdDeleteError = DeleteStudentStudentsStudentIdDeleteErrors[keyof DeleteStudentStudentsStudentIdDeleteErrors];

export type DeleteStudentStudentsStudentIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadStudentStudentsStudentIdGetData = {
    body?: never;
    path: {
        /**
         * ID студента для получения
         */
        student_id: number;
    };
    query?: never;
    url: '/students/{student_id}';
};

export type ReadStudentStudentsStudentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadStudentStudentsStudentIdGetError = ReadStudentStudentsStudentIdGetErrors[keyof ReadStudentStudentsStudentIdGetErrors];

export type ReadStudentStudentsStudentIdGetResponses = {
    /**
     * Successful Response
     */
    200: StudentPrivate;
};

export type ReadStudentStudentsStudentIdGetResponse = ReadStudentStudentsStudentIdGetResponses[keyof ReadStudentStudentsStudentIdGetResponses];

export type UpdateStudentStudentsStudentIdPutData = {
    body: StudentUpdate;
    path: {
        /**
         * ID студента для изменения
         */
        student_id: number;
    };
    query?: never;
    url: '/students/{student_id}';
};

export type UpdateStudentStudentsStudentIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStudentStudentsStudentIdPutError = UpdateStudentStudentsStudentIdPutErrors[keyof UpdateStudentStudentsStudentIdPutErrors];

export type UpdateStudentStudentsStudentIdPutResponses = {
    /**
     * Successful Response
     */
    200: StudentPrivate;
};

export type UpdateStudentStudentsStudentIdPutResponse = UpdateStudentStudentsStudentIdPutResponses[keyof UpdateStudentStudentsStudentIdPutResponses];

export type ReadReferencesStudentsStudentIdPhotosGetData = {
    body?: never;
    path: {
        /**
         * ID студента для получения фотографий
         */
        student_id: number;
    };
    query?: {
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/students/{student_id}/photos/';
};

export type ReadReferencesStudentsStudentIdPhotosGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadReferencesStudentsStudentIdPhotosGetError = ReadReferencesStudentsStudentIdPhotosGetErrors[keyof ReadReferencesStudentsStudentIdPhotosGetErrors];

export type ReadReferencesStudentsStudentIdPhotosGetResponses = {
    /**
     * Response Read References Students  Student Id  Photos  Get
     *
     * Successful Response
     */
    200: Array<ReferenceFacePublic>;
};

export type ReadReferencesStudentsStudentIdPhotosGetResponse = ReadReferencesStudentsStudentIdPhotosGetResponses[keyof ReadReferencesStudentsStudentIdPhotosGetResponses];

export type CreateReferenceStudentsStudentIdPhotosPostData = {
    body: BodyCreateReferenceStudentsStudentIdPhotosPost;
    path: {
        /**
         * ID студента для добавления фотографии
         */
        student_id: number;
    };
    query?: never;
    url: '/students/{student_id}/photos/';
};

export type CreateReferenceStudentsStudentIdPhotosPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateReferenceStudentsStudentIdPhotosPostError = CreateReferenceStudentsStudentIdPhotosPostErrors[keyof CreateReferenceStudentsStudentIdPhotosPostErrors];

export type CreateReferenceStudentsStudentIdPhotosPostResponses = {
    /**
     * Successful Response
     */
    201: ReferenceFacePublic;
};

export type CreateReferenceStudentsStudentIdPhotosPostResponse = CreateReferenceStudentsStudentIdPhotosPostResponses[keyof CreateReferenceStudentsStudentIdPhotosPostResponses];

export type DeleteReferenceStudentsStudentIdPhotosPhotoIdDeleteData = {
    body?: never;
    path: {
        /**
         * ID студента для удаления фотографии
         */
        student_id: number;
        /**
         * ID фотографии для удаления
         */
        photo_id: number;
    };
    query?: never;
    url: '/students/{student_id}/photos/{photo_id}';
};

export type DeleteReferenceStudentsStudentIdPhotosPhotoIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteReferenceStudentsStudentIdPhotosPhotoIdDeleteError = DeleteReferenceStudentsStudentIdPhotosPhotoIdDeleteErrors[keyof DeleteReferenceStudentsStudentIdPhotosPhotoIdDeleteErrors];

export type DeleteReferenceStudentsStudentIdPhotosPhotoIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadReferenceStudentsStudentIdPhotosPhotoIdGetData = {
    body?: never;
    path: {
        /**
         * ID студента для получения фотографии
         */
        student_id: number;
        /**
         * ID фотографии для получения
         */
        photo_id: number;
    };
    query?: never;
    url: '/students/{student_id}/photos/{photo_id}';
};

export type ReadReferenceStudentsStudentIdPhotosPhotoIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadReferenceStudentsStudentIdPhotosPhotoIdGetError = ReadReferenceStudentsStudentIdPhotosPhotoIdGetErrors[keyof ReadReferenceStudentsStudentIdPhotosPhotoIdGetErrors];

export type ReadReferenceStudentsStudentIdPhotosPhotoIdGetResponses = {
    /**
     * Successful Response
     */
    200: ReferenceFacePublic;
};

export type ReadReferenceStudentsStudentIdPhotosPhotoIdGetResponse = ReadReferenceStudentsStudentIdPhotosPhotoIdGetResponses[keyof ReadReferenceStudentsStudentIdPhotosPhotoIdGetResponses];

export type ReadResultsReportsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lecture Date
         */
        lecture_date?: string | null;
        /**
         * Lecture Num
         */
        lecture_num?: number | null;
        /**
         * Stream Id
         */
        stream_id?: number | null;
        /**
         * Group Id
         */
        group_id?: number | null;
        /**
         * Student Id
         */
        student_id?: number | null;
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/reports/';
};

export type ReadResultsReportsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadResultsReportsGetError = ReadResultsReportsGetErrors[keyof ReadResultsReportsGetErrors];

export type ReadResultsReportsGetResponses = {
    /**
     * Response Read Results Reports  Get
     *
     * Successful Response
     */
    200: Array<RecognitionDataPublicWithRecognitionResultAndStudent>;
};

export type ReadResultsReportsGetResponse = ReadResultsReportsGetResponses[keyof ReadResultsReportsGetResponses];

export type CreateResultReportsPostData = {
    body: BodyCreateResultReportsPost;
    path?: never;
    query?: never;
    url: '/reports/';
};

export type CreateResultReportsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateResultReportsPostError = CreateResultReportsPostErrors[keyof CreateResultReportsPostErrors];

export type CreateResultReportsPostResponses = {
    /**
     * Successful Response
     */
    201: RecognitionDataPublic;
};

export type CreateResultReportsPostResponse = CreateResultReportsPostResponses[keyof CreateResultReportsPostResponses];

export type ReadReportReportsDataIdGetData = {
    body?: never;
    path: {
        /**
         * ID отчета для получения
         */
        data_id: number;
    };
    query?: never;
    url: '/reports/{data_id}';
};

export type ReadReportReportsDataIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadReportReportsDataIdGetError = ReadReportReportsDataIdGetErrors[keyof ReadReportReportsDataIdGetErrors];

export type ReadReportReportsDataIdGetResponses = {
    /**
     * Successful Response
     */
    200: RecognitionDataPublicWithRecognitionResultAndStudent;
};

export type ReadReportReportsDataIdGetResponse = ReadReportReportsDataIdGetResponses[keyof ReadReportReportsDataIdGetResponses];

export type UpdateResultReportsResultsResultIdPutData = {
    body: RecognitionResultUpdate;
    path: {
        /**
         * ID результата для изменения
         */
        result_id: number;
    };
    query?: never;
    url: '/reports/results/{result_id}';
};

export type UpdateResultReportsResultsResultIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateResultReportsResultsResultIdPutError = UpdateResultReportsResultsResultIdPutErrors[keyof UpdateResultReportsResultsResultIdPutErrors];

export type UpdateResultReportsResultsResultIdPutResponses = {
    /**
     * Successful Response
     */
    200: RecognitionResultPublicWithStudent;
};

export type UpdateResultReportsResultsResultIdPutResponse = UpdateResultReportsResultsResultIdPutResponses[keyof UpdateResultReportsResultsResultIdPutResponses];

export type LoginForAccessTokenTokenPostData = {
    body: BodyLoginForAccessTokenTokenPost;
    path?: never;
    query?: never;
    url: '/token/';
};

export type LoginForAccessTokenTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginForAccessTokenTokenPostError = LoginForAccessTokenTokenPostErrors[keyof LoginForAccessTokenTokenPostErrors];

export type LoginForAccessTokenTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginForAccessTokenTokenPostResponse = LoginForAccessTokenTokenPostResponses[keyof LoginForAccessTokenTokenPostResponses];

export type ReadUsersMeUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/';
};

export type ReadUsersMeUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUsersMeUsersMeGetResponse = ReadUsersMeUsersMeGetResponses[keyof ReadUsersMeUsersMeGetResponses];

export type ReadAllUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/';
};

export type ReadAllUsersUsersGetResponses = {
    /**
     * Response Read All Users Users  Get
     *
     * Successful Response
     */
    200: Array<UserPublic>;
};

export type ReadAllUsersUsersGetResponse = ReadAllUsersUsersGetResponses[keyof ReadAllUsersUsersGetResponses];
