// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_create_reference_api_students__student_id__photos__post
 */
export type BodyCreateReferenceApiStudentsStudentIdPhotosPost = {
    /**
     * Photo
     */
    photo: Blob | File;
};

/**
 * Body_create_result_api_reports__post
 */
export type BodyCreateResultApiReportsPost = {
    /**
     * Data
     */
    data: RecognitionDataCreate | string;
    /**
     * Photo
     */
    photo: Blob | File;
};

/**
 * Body_login_for_access_token_api_token__post
 */
export type BodyLoginForAccessTokenApiTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * GroupCreate
 */
export type GroupCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Stream Id
     */
    stream_id: number;
};

/**
 * GroupPublic
 */
export type GroupPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Stream Id
     */
    stream_id: number;
    /**
     * Id
     */
    id: number;
};

/**
 * GroupPublicWithStream
 */
export type GroupPublicWithStream = {
    /**
     * Name
     */
    name: string;
    /**
     * Stream Id
     */
    stream_id: number;
    /**
     * Id
     */
    id: number;
    stream: StreamPublic;
};

/**
 * GroupUpdate
 */
export type GroupUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Stream Id
     */
    stream_id?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RecognitionDataCreate
 */
export type RecognitionDataCreate = {
    /**
     * Lecture Date
     */
    lecture_date?: string;
    /**
     * Lecture Num
     */
    lecture_num: number;
};

/**
 * RecognitionDataPublic
 */
export type RecognitionDataPublic = {
    /**
     * Lecture Date
     */
    lecture_date?: string;
    /**
     * Lecture Num
     */
    lecture_num: number;
    /**
     * Id
     */
    id: number;
    /**
     * Image Path
     */
    image_path: string;
};

/**
 * RecognitionDataPublicWithRecognitionResultAndStudent
 */
export type RecognitionDataPublicWithRecognitionResultAndStudent = {
    /**
     * Lecture Date
     */
    lecture_date?: string;
    /**
     * Lecture Num
     */
    lecture_num: number;
    /**
     * Id
     */
    id: number;
    /**
     * Image Path
     */
    image_path: string;
    /**
     * Results
     */
    results: Array<RecognitionResultPublicWithStudent>;
};

/**
 * RecognitionResultPublicWithStudent
 */
export type RecognitionResultPublicWithStudent = {
    /**
     * Student Id
     */
    student_id?: number | null;
    /**
     * Data Id
     */
    data_id: number;
    /**
     * Bbox X1
     */
    bbox_x1: number;
    /**
     * Bbox Y1
     */
    bbox_y1: number;
    /**
     * Bbox X2
     */
    bbox_x2: number;
    /**
     * Bbox Y2
     */
    bbox_y2: number;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Similarity
     */
    similarity?: number | null;
    /**
     * Id
     */
    id: number;
    student?: StudentPublic | null;
};

/**
 * RecognitionResultUpdate
 */
export type RecognitionResultUpdate = {
    /**
     * Student Id
     */
    student_id?: number | null;
    /**
     * Similarity
     */
    similarity?: null;
};

/**
 * ReferenceFacePublic
 */
export type ReferenceFacePublic = {
    /**
     * Student Id
     */
    student_id: number;
    /**
     * Id
     */
    id: number;
    /**
     * Image Path
     */
    image_path: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * StreamCreate
 */
export type StreamCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * StreamPublic
 */
export type StreamPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: number;
};

/**
 * StreamUpdate
 */
export type StreamUpdate = {
    [key: string]: unknown;
};

/**
 * StudentCreate
 */
export type StudentCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Group Id
     */
    group_id: number;
    /**
     * Phone Number
     */
    phone_number?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * StudentPrivate
 */
export type StudentPrivate = {
    /**
     * Name
     */
    name: string;
    /**
     * Group Id
     */
    group_id: number;
    /**
     * Id
     */
    id: number;
    /**
     * Phone Number
     */
    phone_number: string | null;
    /**
     * Email
     */
    email: string | null;
};

/**
 * StudentPublic
 */
export type StudentPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Group Id
     */
    group_id: number;
    /**
     * Id
     */
    id: number;
};

/**
 * StudentPublicWithGroup
 */
export type StudentPublicWithGroup = {
    /**
     * Name
     */
    name: string;
    /**
     * Group Id
     */
    group_id: number;
    /**
     * Id
     */
    id: number;
    group: GroupPublic;
};

/**
 * StudentUpdate
 */
export type StudentUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Group Id
     */
    group_id?: number | null;
    /**
     * Phone Number
     */
    phone_number?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * User Name
     */
    user_name: string;
    /**
     * Role Id
     */
    role_id: number | null;
    /**
     * Student Id
     */
    student_id?: number | null;
    /**
     * Group Id
     */
    group_id?: number | null;
    /**
     * Stream Id
     */
    stream_id?: number | null;
    /**
     * Id
     */
    id: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadStreamsApiStreamsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/api/streams/';
};

export type ReadStreamsApiStreamsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadStreamsApiStreamsGetError = ReadStreamsApiStreamsGetErrors[keyof ReadStreamsApiStreamsGetErrors];

export type ReadStreamsApiStreamsGetResponses = {
    /**
     * Response Read Streams Api Streams  Get
     *
     * Successful Response
     */
    200: Array<StreamPublic>;
};

export type ReadStreamsApiStreamsGetResponse = ReadStreamsApiStreamsGetResponses[keyof ReadStreamsApiStreamsGetResponses];

export type CreateStreamApiStreamsPostData = {
    body: StreamCreate;
    path?: never;
    query?: never;
    url: '/api/streams/';
};

export type CreateStreamApiStreamsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStreamApiStreamsPostError = CreateStreamApiStreamsPostErrors[keyof CreateStreamApiStreamsPostErrors];

export type CreateStreamApiStreamsPostResponses = {
    /**
     * Successful Response
     */
    201: StreamPublic;
};

export type CreateStreamApiStreamsPostResponse = CreateStreamApiStreamsPostResponses[keyof CreateStreamApiStreamsPostResponses];

export type DeleteStreamApiStreamsStreamIdDeleteData = {
    body?: never;
    path: {
        /**
         * ID потока для удаления
         */
        stream_id: number;
    };
    query?: never;
    url: '/api/streams/{stream_id}';
};

export type DeleteStreamApiStreamsStreamIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteStreamApiStreamsStreamIdDeleteError = DeleteStreamApiStreamsStreamIdDeleteErrors[keyof DeleteStreamApiStreamsStreamIdDeleteErrors];

export type DeleteStreamApiStreamsStreamIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadStreamApiStreamsStreamIdGetData = {
    body?: never;
    path: {
        /**
         * ID потока для получения
         */
        stream_id: number;
    };
    query?: never;
    url: '/api/streams/{stream_id}';
};

export type ReadStreamApiStreamsStreamIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadStreamApiStreamsStreamIdGetError = ReadStreamApiStreamsStreamIdGetErrors[keyof ReadStreamApiStreamsStreamIdGetErrors];

export type ReadStreamApiStreamsStreamIdGetResponses = {
    /**
     * Successful Response
     */
    200: StreamPublic;
};

export type ReadStreamApiStreamsStreamIdGetResponse = ReadStreamApiStreamsStreamIdGetResponses[keyof ReadStreamApiStreamsStreamIdGetResponses];

export type UpdateStreamApiStreamsStreamIdPutData = {
    body: StreamUpdate;
    path: {
        /**
         * ID потока для изменения
         */
        stream_id: number;
    };
    query?: never;
    url: '/api/streams/{stream_id}';
};

export type UpdateStreamApiStreamsStreamIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStreamApiStreamsStreamIdPutError = UpdateStreamApiStreamsStreamIdPutErrors[keyof UpdateStreamApiStreamsStreamIdPutErrors];

export type UpdateStreamApiStreamsStreamIdPutResponses = {
    /**
     * Successful Response
     */
    200: StreamPublic;
};

export type UpdateStreamApiStreamsStreamIdPutResponse = UpdateStreamApiStreamsStreamIdPutResponses[keyof UpdateStreamApiStreamsStreamIdPutResponses];

export type ReadGroupsApiGroupsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Stream Id
         */
        stream_id?: number | null;
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/api/groups/';
};

export type ReadGroupsApiGroupsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadGroupsApiGroupsGetError = ReadGroupsApiGroupsGetErrors[keyof ReadGroupsApiGroupsGetErrors];

export type ReadGroupsApiGroupsGetResponses = {
    /**
     * Response Read Groups Api Groups  Get
     *
     * Successful Response
     */
    200: Array<GroupPublicWithStream>;
};

export type ReadGroupsApiGroupsGetResponse = ReadGroupsApiGroupsGetResponses[keyof ReadGroupsApiGroupsGetResponses];

export type CreateGroupApiGroupsPostData = {
    body: GroupCreate;
    path?: never;
    query?: never;
    url: '/api/groups/';
};

export type CreateGroupApiGroupsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGroupApiGroupsPostError = CreateGroupApiGroupsPostErrors[keyof CreateGroupApiGroupsPostErrors];

export type CreateGroupApiGroupsPostResponses = {
    /**
     * Successful Response
     */
    201: GroupPublicWithStream;
};

export type CreateGroupApiGroupsPostResponse = CreateGroupApiGroupsPostResponses[keyof CreateGroupApiGroupsPostResponses];

export type DeleteGroupApiGroupsGroupIdDeleteData = {
    body?: never;
    path: {
        /**
         * ID группы для удаления
         */
        group_id: number;
    };
    query?: never;
    url: '/api/groups/{group_id}';
};

export type DeleteGroupApiGroupsGroupIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGroupApiGroupsGroupIdDeleteError = DeleteGroupApiGroupsGroupIdDeleteErrors[keyof DeleteGroupApiGroupsGroupIdDeleteErrors];

export type DeleteGroupApiGroupsGroupIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadGroupApiGroupsGroupIdGetData = {
    body?: never;
    path: {
        /**
         * ID группы для получения
         */
        group_id: number;
    };
    query?: never;
    url: '/api/groups/{group_id}';
};

export type ReadGroupApiGroupsGroupIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadGroupApiGroupsGroupIdGetError = ReadGroupApiGroupsGroupIdGetErrors[keyof ReadGroupApiGroupsGroupIdGetErrors];

export type ReadGroupApiGroupsGroupIdGetResponses = {
    /**
     * Successful Response
     */
    200: GroupPublicWithStream;
};

export type ReadGroupApiGroupsGroupIdGetResponse = ReadGroupApiGroupsGroupIdGetResponses[keyof ReadGroupApiGroupsGroupIdGetResponses];

export type UpdateGroupApiGroupsGroupIdPutData = {
    body: GroupUpdate;
    path: {
        /**
         * ID группы для изменения
         */
        group_id: number;
    };
    query?: never;
    url: '/api/groups/{group_id}';
};

export type UpdateGroupApiGroupsGroupIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateGroupApiGroupsGroupIdPutError = UpdateGroupApiGroupsGroupIdPutErrors[keyof UpdateGroupApiGroupsGroupIdPutErrors];

export type UpdateGroupApiGroupsGroupIdPutResponses = {
    /**
     * Successful Response
     */
    200: GroupPublicWithStream;
};

export type UpdateGroupApiGroupsGroupIdPutResponse = UpdateGroupApiGroupsGroupIdPutResponses[keyof UpdateGroupApiGroupsGroupIdPutResponses];

export type ReadStudentsApiStudentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Group Id
         */
        group_id?: number | null;
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/api/students/';
};

export type ReadStudentsApiStudentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadStudentsApiStudentsGetError = ReadStudentsApiStudentsGetErrors[keyof ReadStudentsApiStudentsGetErrors];

export type ReadStudentsApiStudentsGetResponses = {
    /**
     * Response Read Students Api Students  Get
     *
     * Successful Response
     */
    200: Array<StudentPublicWithGroup>;
};

export type ReadStudentsApiStudentsGetResponse = ReadStudentsApiStudentsGetResponses[keyof ReadStudentsApiStudentsGetResponses];

export type CreateStudentApiStudentsPostData = {
    body: StudentCreate;
    path?: never;
    query?: never;
    url: '/api/students/';
};

export type CreateStudentApiStudentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStudentApiStudentsPostError = CreateStudentApiStudentsPostErrors[keyof CreateStudentApiStudentsPostErrors];

export type CreateStudentApiStudentsPostResponses = {
    /**
     * Successful Response
     */
    201: StudentPublic;
};

export type CreateStudentApiStudentsPostResponse = CreateStudentApiStudentsPostResponses[keyof CreateStudentApiStudentsPostResponses];

export type DeleteStudentApiStudentsStudentIdDeleteData = {
    body?: never;
    path: {
        /**
         * ID студента для удаления
         */
        student_id: number;
    };
    query?: never;
    url: '/api/students/{student_id}';
};

export type DeleteStudentApiStudentsStudentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteStudentApiStudentsStudentIdDeleteError = DeleteStudentApiStudentsStudentIdDeleteErrors[keyof DeleteStudentApiStudentsStudentIdDeleteErrors];

export type DeleteStudentApiStudentsStudentIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadStudentApiStudentsStudentIdGetData = {
    body?: never;
    path: {
        /**
         * ID студента для получения
         */
        student_id: number;
    };
    query?: never;
    url: '/api/students/{student_id}';
};

export type ReadStudentApiStudentsStudentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadStudentApiStudentsStudentIdGetError = ReadStudentApiStudentsStudentIdGetErrors[keyof ReadStudentApiStudentsStudentIdGetErrors];

export type ReadStudentApiStudentsStudentIdGetResponses = {
    /**
     * Successful Response
     */
    200: StudentPrivate;
};

export type ReadStudentApiStudentsStudentIdGetResponse = ReadStudentApiStudentsStudentIdGetResponses[keyof ReadStudentApiStudentsStudentIdGetResponses];

export type UpdateStudentApiStudentsStudentIdPutData = {
    body: StudentUpdate;
    path: {
        /**
         * ID студента для изменения
         */
        student_id: number;
    };
    query?: never;
    url: '/api/students/{student_id}';
};

export type UpdateStudentApiStudentsStudentIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStudentApiStudentsStudentIdPutError = UpdateStudentApiStudentsStudentIdPutErrors[keyof UpdateStudentApiStudentsStudentIdPutErrors];

export type UpdateStudentApiStudentsStudentIdPutResponses = {
    /**
     * Successful Response
     */
    200: StudentPrivate;
};

export type UpdateStudentApiStudentsStudentIdPutResponse = UpdateStudentApiStudentsStudentIdPutResponses[keyof UpdateStudentApiStudentsStudentIdPutResponses];

export type ReadReferencesApiStudentsStudentIdPhotosGetData = {
    body?: never;
    path: {
        /**
         * ID студента для получения фотографий
         */
        student_id: number;
    };
    query?: {
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/api/students/{student_id}/photos/';
};

export type ReadReferencesApiStudentsStudentIdPhotosGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadReferencesApiStudentsStudentIdPhotosGetError = ReadReferencesApiStudentsStudentIdPhotosGetErrors[keyof ReadReferencesApiStudentsStudentIdPhotosGetErrors];

export type ReadReferencesApiStudentsStudentIdPhotosGetResponses = {
    /**
     * Response Read References Api Students  Student Id  Photos  Get
     *
     * Successful Response
     */
    200: Array<ReferenceFacePublic>;
};

export type ReadReferencesApiStudentsStudentIdPhotosGetResponse = ReadReferencesApiStudentsStudentIdPhotosGetResponses[keyof ReadReferencesApiStudentsStudentIdPhotosGetResponses];

export type CreateReferenceApiStudentsStudentIdPhotosPostData = {
    body: BodyCreateReferenceApiStudentsStudentIdPhotosPost;
    path: {
        /**
         * ID студента для добавления фотографии
         */
        student_id: number;
    };
    query?: never;
    url: '/api/students/{student_id}/photos/';
};

export type CreateReferenceApiStudentsStudentIdPhotosPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateReferenceApiStudentsStudentIdPhotosPostError = CreateReferenceApiStudentsStudentIdPhotosPostErrors[keyof CreateReferenceApiStudentsStudentIdPhotosPostErrors];

export type CreateReferenceApiStudentsStudentIdPhotosPostResponses = {
    /**
     * Successful Response
     */
    201: ReferenceFacePublic;
};

export type CreateReferenceApiStudentsStudentIdPhotosPostResponse = CreateReferenceApiStudentsStudentIdPhotosPostResponses[keyof CreateReferenceApiStudentsStudentIdPhotosPostResponses];

export type DeleteReferenceApiStudentsStudentIdPhotosPhotoIdDeleteData = {
    body?: never;
    path: {
        /**
         * ID студента для удаления фотографии
         */
        student_id: number;
        /**
         * ID фотографии для удаления
         */
        photo_id: number;
    };
    query?: never;
    url: '/api/students/{student_id}/photos/{photo_id}';
};

export type DeleteReferenceApiStudentsStudentIdPhotosPhotoIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteReferenceApiStudentsStudentIdPhotosPhotoIdDeleteError = DeleteReferenceApiStudentsStudentIdPhotosPhotoIdDeleteErrors[keyof DeleteReferenceApiStudentsStudentIdPhotosPhotoIdDeleteErrors];

export type DeleteReferenceApiStudentsStudentIdPhotosPhotoIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadReferenceApiStudentsStudentIdPhotosPhotoIdGetData = {
    body?: never;
    path: {
        /**
         * ID студента для получения фотографии
         */
        student_id: number;
        /**
         * ID фотографии для получения
         */
        photo_id: number;
    };
    query?: never;
    url: '/api/students/{student_id}/photos/{photo_id}';
};

export type ReadReferenceApiStudentsStudentIdPhotosPhotoIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadReferenceApiStudentsStudentIdPhotosPhotoIdGetError = ReadReferenceApiStudentsStudentIdPhotosPhotoIdGetErrors[keyof ReadReferenceApiStudentsStudentIdPhotosPhotoIdGetErrors];

export type ReadReferenceApiStudentsStudentIdPhotosPhotoIdGetResponses = {
    /**
     * Successful Response
     */
    200: ReferenceFacePublic;
};

export type ReadReferenceApiStudentsStudentIdPhotosPhotoIdGetResponse = ReadReferenceApiStudentsStudentIdPhotosPhotoIdGetResponses[keyof ReadReferenceApiStudentsStudentIdPhotosPhotoIdGetResponses];

export type ReadResultsApiReportsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lecture Date
         */
        lecture_date?: string | null;
        /**
         * Lecture Num
         */
        lecture_num?: number | null;
        /**
         * Stream Id
         */
        stream_id?: number | null;
        /**
         * Group Id
         */
        group_id?: number | null;
        /**
         * Student Id
         */
        student_id?: number | null;
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/api/reports/';
};

export type ReadResultsApiReportsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadResultsApiReportsGetError = ReadResultsApiReportsGetErrors[keyof ReadResultsApiReportsGetErrors];

export type ReadResultsApiReportsGetResponses = {
    /**
     * Response Read Results Api Reports  Get
     *
     * Successful Response
     */
    200: Array<RecognitionDataPublicWithRecognitionResultAndStudent>;
};

export type ReadResultsApiReportsGetResponse = ReadResultsApiReportsGetResponses[keyof ReadResultsApiReportsGetResponses];

export type CreateResultApiReportsPostData = {
    body: BodyCreateResultApiReportsPost;
    path?: never;
    query?: never;
    url: '/api/reports/';
};

export type CreateResultApiReportsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateResultApiReportsPostError = CreateResultApiReportsPostErrors[keyof CreateResultApiReportsPostErrors];

export type CreateResultApiReportsPostResponses = {
    /**
     * Successful Response
     */
    201: RecognitionDataPublic;
};

export type CreateResultApiReportsPostResponse = CreateResultApiReportsPostResponses[keyof CreateResultApiReportsPostResponses];

export type ReadReportApiReportsDataIdGetData = {
    body?: never;
    path: {
        /**
         * ID отчета для получения
         */
        data_id: number;
    };
    query?: never;
    url: '/api/reports/{data_id}';
};

export type ReadReportApiReportsDataIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadReportApiReportsDataIdGetError = ReadReportApiReportsDataIdGetErrors[keyof ReadReportApiReportsDataIdGetErrors];

export type ReadReportApiReportsDataIdGetResponses = {
    /**
     * Successful Response
     */
    200: RecognitionDataPublicWithRecognitionResultAndStudent;
};

export type ReadReportApiReportsDataIdGetResponse = ReadReportApiReportsDataIdGetResponses[keyof ReadReportApiReportsDataIdGetResponses];

export type UpdateResultApiReportsResultsResultIdPutData = {
    body: RecognitionResultUpdate;
    path: {
        /**
         * ID результата для изменения
         */
        result_id: number;
    };
    query?: never;
    url: '/api/reports/results/{result_id}';
};

export type UpdateResultApiReportsResultsResultIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateResultApiReportsResultsResultIdPutError = UpdateResultApiReportsResultsResultIdPutErrors[keyof UpdateResultApiReportsResultsResultIdPutErrors];

export type UpdateResultApiReportsResultsResultIdPutResponses = {
    /**
     * Successful Response
     */
    200: RecognitionResultPublicWithStudent;
};

export type UpdateResultApiReportsResultsResultIdPutResponse = UpdateResultApiReportsResultsResultIdPutResponses[keyof UpdateResultApiReportsResultsResultIdPutResponses];

export type LoginForAccessTokenApiTokenPostData = {
    body: BodyLoginForAccessTokenApiTokenPost;
    path?: never;
    query?: never;
    url: '/api/token/';
};

export type LoginForAccessTokenApiTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginForAccessTokenApiTokenPostError = LoginForAccessTokenApiTokenPostErrors[keyof LoginForAccessTokenApiTokenPostErrors];

export type LoginForAccessTokenApiTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginForAccessTokenApiTokenPostResponse = LoginForAccessTokenApiTokenPostResponses[keyof LoginForAccessTokenApiTokenPostResponses];

export type ReadUsersMeApiUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type ReadUsersMeApiUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUsersMeApiUsersMeGetResponse = ReadUsersMeApiUsersMeGetResponses[keyof ReadUsersMeApiUsersMeGetResponses];

export type ReadAllUsersApiUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type ReadAllUsersApiUsersGetResponses = {
    /**
     * Response Read All Users Api Users  Get
     *
     * Successful Response
     */
    200: Array<UserPublic>;
};

export type ReadAllUsersApiUsersGetResponse = ReadAllUsersApiUsersGetResponses[keyof ReadAllUsersApiUsersGetResponses];
